apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubewars-admission-hook-{{ .Release.Name }}
  labels:
    app: kubewars-admission-hook-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubewars-admission-hook-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: kubewars-admission-hook-{{ .Release.Name }}
    spec:
      containers:
        - name: kubewars-admission-hook
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: CERT_PATH
              value: /etc/webhook/certs/cert.pem
            - name: KEY_PATH
              value: /etc/webhook/certs/key.pem
            - name: TLS
              value: "True"
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: kubewars-admission-hook-tls
